# Generated by Django 3.2.3 on 2021-06-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsignin',
            name='photoUrl',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(default='userPics/blankUserProfile.png', null=True, upload_to='userPics'),
        ),
    ]
